sources:
  - name: host1 # The name of the host to be backed up

    host: user:password@host1:port # Hostname of the remote host (use 'localhost' for local backups)

    handlers:
    - handler: files # enable Files backup
      mode: incremental # available modes: full, incremental, archive. Default: incremental
      limit: [/etc, /home, /root] # list of files/directories to backup - optional (if no paths are provided, all contents from / will be included, except the ones in the exclude list)
      exclude: ['/etc/passwd'] # list of files/directories to exclude from the backup - optional
      bwlimit: # limit the bandwidth - optional

    - handler: openwrt # enable OpenWrt config backup

    - handler: truenas # enable TrueNAS config backup

    - handler: zfs_datasets # enable ZFS datasets backup
      limit: [dataset1, dataset2] # list of datasets to backup - optional (if no datasets are provided, all datasets will be included, except the ones in the exclude list)
      exclude: [dataset3] # list of datasets to exclude from the backup - optional

    - handler: homeassistant # enable Home Assistant config backup

    - handler: proxmox_vms # enable Proxmox VMs backup
      mode: snapshot # available modes: snapshot, suspend, stop. Default: snapshot
      compress: zstd # available modes: gzip, lz4, zstd. Default: zstd
      limit: [vm1, vm2] # list of VMs to backup - optional (if no VMs are provided, all VMs will be included, except the ones in the exclude list)
      exclude: [vm3] # list of VMs to exclude from the backup - optional
      bwlimit: # limit the bandwidth - optional

storages:
  - name: storage1 # The name of the storage to be used

    path: /path/to/storage1 # Path to the storage to be used

jobs:
  - name: job1 # The name of the backup job

    type: backup # Type of job to be performed. Available types: backup (replication coming soon)

    dest: storage1 # Destination storage to be used when performing the job

    schedule: 0 0 * * * # Cron schedule to be used when running the job. Default: 0 0 * * *

    limit: [host1] # list of hosts for the backup job - optional (if no hosts are provided, all hosts will be included, except the ones in the exclude list)

    exclude: [host2] # list of hosts to exclude from the backup job - optional

    retention_policy: # Pruning policy to be applied to versions - optional (if no policy is provided, all versions will be kept indefinitely)
      last: 3 # Number of last versions to keep (this ensures that the last N versions are kept, regardless of the other policies)
      hourly: 24 # Number of hourly versions to keep
      daily: 7 # Number of daily versions to keep
      weekly: 4 # Number of weekly versions to keep
      monthly: 12 # Number of monthly versions to keep
      yearly: 5 # Number of yearly versions to keep

    notification_policy: always # The notification policy. Available policies: always, on-failure, never. Default: always

    concurrency: 1 # Number of concurrent hosts to be backed up. Default: 1

    pre_run_cmd: /path/to/pre_run.sh # Command to be executed before performing the job - optional

    post_run_cmd: /path/to/post_run.sh # Command to be executed after performing the job - optional

notifiers:
  - handler: email # enable email report
    sender: from@example.com # Email from address to be used in the email report
    to: [email@emample.com] # Email addresses to be used when sending the email report
    command: sendmail -t # Custom email command. Optional
  - handler: slack # enable slack report
    token: # Slack token to be used when sending the slack report
    channel: '#general' # Slack channel to be used when sending the slack report