hosts:
  - name: host1
    host: user:password@host1:port # Hostname of the remote host
    backup:
    - handler: files # enable Files backup
      mode: incremental # available modes: full, incremental, archive. Default: incremental
      limit: [/etc, /home, /root] # list of files/directories to backup - optional (if no paths are provided, all contents from / will be included, except the ones in the exclude list)
      exclude: ['/etc/passwd'] # list of files/directories to exclude from the backup - optional
      bwlimit: # limit the bandwidth - optional

    - handler: openwrt_config # enable OpenWrt config backup

    - handler: truenas_config # enable TrueNAS config backup

    - handler: zfs_datasets # enable ZFS datasets backup
      limit: [dataset1, dataset2] # list of datasets to backup - optional (if no datasets are provided, all datasets will be included, except the ones in the exclude list)
      exclude: [dataset3] # list of datasets to exclude from the backup - optional

    - handler: homeassistant_config # enable Home Assistant config backup

    - handler: proxmox_vms # enable Proxmox VMs backup
      mode: snapshot # available modes: snapshot, suspend, stop. Default: snapshot
      compress: zstd # available modes: gzip, lz4, zstd. Default: zstd
      limit: [vm1, vm2] # list of VMs to backup - optional (if no VMs are provided, all VMs will be included, except the ones in the exclude list)
      exclude: [vm3] # list of VMs to exclude from the backup - optional
      bwlimit: # limit the bandwidth - optional

jobs:
  - name: job1 # The name of the backup job
    
    dest: /path/to/backup # Destination path to be used when performing the backup. If no destination is provided, the default-dest will be used

    limit: [host1] # list of hosts for the backup job - optional (if no hosts are provided, all hosts will be included, except the ones in the exclude list)

    exclude: [host2] # list of hosts to exclude from the backup job - optional

    schedule: 0 0 * * * # Cron schedule to be used when performing the backup. Default: 0 0 * * *

    retention-policy: # The policy to be applied to the backup job - optional (if no policy is provided, all backups will be kept indefinitely)
      last: 3 # Number of last backups to keep (this ensures that the last N backups are kept, regardless of the other policies)
      hourly: 24 # Number of hourly backups to keep
      daily: 7 # Number of daily backups to keep
      weekly: 4 # Number of weekly backups to keep
      monthly: 12 # Number of monthly backups to keep
      yearly: 5 # Number of yearly backups to keep

    notification-policy: always # The notification policy. Available policies: always, on-failure, never. Default: always

    concurrency: 1 # Number of concurrent hosts to be backed up. Default: 1

    pre-backup-cmd: /path/to/pre_backup.sh # Command to be executed before performing the backup job - optional

    post-backup-cmd: /path/to/post_backup.sh # Command to be executed after performing the backup job - optional

notification:
  - handler: email # enable email report
    from: from@example.com # Email from address to be used in the email report
    to: [email@emample.com] # Email addresses to be used when sending the email report
    command: sendmail -t # Custom email command. Optional
  - handler: slack # enable slack report
    token: # Slack token to be used when sending the slack report
    channel: '#general' # Slack channel to be used when sending the slack report