__app_name__ = "UsBackup"
__package_name__ = "usbackup"
__version__ = "2.2.16"
__description__ = "SSH based modular backup tool featuring hosts, retention policies, backup handlers and report handlers"
__author__ = "Septimiu Ujica"
__author_email__ = "hellp@septi.ro"
__author_url__ = "https://www.septi.ro"
__license__ = "GPLv3"
