__app_name__ = "UsBackup"
__version__ = "0.1.8"
__description__ = "A linux backup tool featuring snapshots, retention policies, backup handlers and report handlers"
__author__ = "Septimiu Ujica"
__author_email__ = "me@septi.ro"
__author_url__ = "https://www.septi.ro"
__license__ = "GPLv3"
